#!/bin/bash

# Define variables
SOURCE="/var/log/messages"
DESTINATION="user@ipofbackupserver:/pathonthebackup"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")

eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa

# Use rsync to backup with a timestamp
rsync -avrz $SOURCE ${DESTINATION}_${TIMESTAMP}

# Print completion message
echo "Backup completed for $SOURCE to ${DESTINATION}_${TIMESTAMP}"
